### ISSUE TITLE
Wired Redstone Missing Recipes

### ISSUE THREAD

**Issue by Kneelawk** [Kneelawk/Innovation-Timespace-5#2]
Wired Redstone doesn't have recipes for any of its items.

Wired Redstone is currently still working on the mechanics for its recipe system.

**Comment by Kneelawk** [comment]
In the meantime, I'll see if I can make a datapack to fix this when I can.

**Comment by JieningYu** [comment]
You can use KubeJS(which can be used on Quilt now)'s global data overrides function to fix this issue or use its JS functions to add recipe smoothly.

**Comment by JieningYu** [comment]
Also the author of QSL should be team QuiltMC because it's not only made by the 2 guys.
<img width="757" alt="image" src="https://user-images.githubusercontent.com/61787533/170497439-4df33972-7566-4a26-9329-e5feccb9c937.png">

**Comment by Kneelawk** [comment]
Wired Redstone v0.3.0 adds recipes, so updating it has fixed this issue.

Also, thanks for reminding me to fix the QSL attribution.
